### ISSUE TITLE
La descripción del repositorio Git pone (USTED) para casual

### ISSUE THREAD

**Issue by ghost** [phpBB-Spain/3.2_Casual_Honorifics#1]
![captura de pantalla de 2016-06-10 21-34-24](https://cloud.githubusercontent.com/assets/174885/15982904/4ca2c658-2f53-11e6-8006-3d021ae7a871.png)

Se trata de un pequeño fallo al copiar-pegar en la configuración de Git describe o de la descripción de GitHub. Debería poner `(TÚ)` en lugar de `(USTED)`.

Puesto que esto está fuera del alcance del contenido de archivos de git, no se puede arreglar con un pull request sino por un administrador del proyecto en GitHub.

Saludos.

**Comment by phpbb-es** [comment]
@fdelapena corregido, se me olvido comentarlo antes, perdona.
